"""Password hashing and session tokens - stdlib only (``hashlib.pbkdf2_hmac`` + ``secrets``), no
extra dependency such as passlib, bcrypt or PyJWT for what is a small, self-hosted user base.

A session or password-reset token travels in clear (cookie, e-mailed link) but is stored only as
its SHA-256 (:func:`hash_token`): a copy of the database opens no session. A plain hash is enough -
the token is 256 random bits, nothing to brute-force, unlike a password.
"""

from __future__ import annotations

import hashlib
import os
import secrets
from datetime import datetime, timedelta, timezone

from ...kernel import mail

SESSION_COOKIE = "spectre_session"
SESSION_LIFETIME = timedelta(days=14)
PASSWORD_RESET_LIFETIME = timedelta(hours=1)
INVITATION_LIFETIME = timedelta(days=14)
_PBKDF2_ITERATIONS = 200_000


def hash_password(password: str, *, salt: str | None = None) -> tuple[str, str]:
    """Return ``(password_hash, salt)``, both hex-encoded. Pass ``salt`` back in to verify a
    password against an existing hash instead of generating a fresh one.
    """
    salt = salt or secrets.token_hex(16)
    digest = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), bytes.fromhex(salt), _PBKDF2_ITERATIONS)
    return digest.hex(), salt


def verify_password(password: str, password_hash: str, salt: str) -> bool:
    candidate, _ = hash_password(password, salt=salt)
    return secrets.compare_digest(candidate, password_hash)


def new_session_token() -> str:
    return secrets.token_urlsafe(32)


def hash_token(token: str) -> str:
    """What the database keeps of a session or password-reset token."""
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


def session_cookie_secure() -> bool:
    """Whether the session cookie carries ``Secure`` (sent over HTTPS only): ``SPECTRE_COOKIE_SECURE``
    when set (``1``/``true``/``yes``/``on``, anything else turns it off), otherwise whenever
    ``SPECTRE_BASE_URL`` is an ``https://`` address. Off by default - a local ``http://``
    instance would otherwise never keep its session.
    """
    explicit = os.environ.get("SPECTRE_COOKIE_SECURE")
    if explicit is not None:
        return explicit.strip().lower() in ("1", "true", "yes", "on")
    return mail.base_url().lower().startswith("https://")


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _sql_datetime(dt: datetime) -> str:
    """``YYYY-MM-DD HH:MM:SS`` in UTC - the same format/timezone SQLite's own ``datetime('now')``
    produces, so ``expires_at`` stays directly comparable to it in SQL (``>``, string-ordered).
    """
    return dt.astimezone(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")


def session_expiry() -> str:
    return _sql_datetime(utcnow() + SESSION_LIFETIME)


def new_token() -> str:
    """A random, URL-safe token - used for password-reset links and microproject invitations, same
    shape as a session token but generated by a separate call so the two are never confused.
    """
    return secrets.token_urlsafe(32)


def password_reset_expiry() -> str:
    return _sql_datetime(utcnow() + PASSWORD_RESET_LIFETIME)


def invitation_expiry() -> str:
    return _sql_datetime(utcnow() + INVITATION_LIFETIME)
